Minor code review for fun, since Daniel mentioned he'd posted BASH code.

diff --git a/sdrestore b/sdrestore
--- a/sdrestore
+++ b/sdrestore
@@ -9,13 +9,12 @@
 
 
 # Settings
-THISAPP=sdrestore
-TEMPFOLDER=/tmp/sdbackup
+THISAPP="$(basename "$0")"
 SETTINGSFILE=~/.sdbackup
 DEFAULTDEV=""
 
 # Automatically install what we need
-if [[ ! `type -P "unp"` || ! `type -P "ddrescue"` || ! `type -P "lshw"` ]]; then
+if [[ ! $(type -P "unp") || ! $(type -P "ddrescue") || ! $(type -P "lshw") ]]; then
   echo "It looks like this is the first time $THISAPP has been run."
   echo "Installing required packages..."
   echo
@@ -25,8 +24,9 @@ if [[ ! `type -P "unp"` || ! `type -P "ddrescue"` || ! `type -P "lshw"` ]]; then
 fi
 
 # Create the temporary folder if it doesn't already exist
-if [[ ! -d "$TEMPFOLDER" ]]; then
-  mkdir "$TEMPFOLDER" || { echo "Error: Cannot create temporary folder" 1>&2; exit 1; }
+if ! TEMPFOLDER="$(mktemp -td sdbackup.tmp.XXXXXXXX)"; then
+  echo "Error: Cannot create temporary folder" 1>&2
+  exit 1
 fi
 
 # Check filename parameter is present
@@ -56,36 +56,43 @@ else
 
   # Get the default
   if [[ -f "$SETTINGSFILE" ]]; then
-    DEFAULTDEV=`cat "$SETTINGSFILE"`
+    DEFAULTDEV="$(cat "$SETTINGSFILE")"
   fi
 
   # Scan for disks
   echo "Scanning drives..."
+  declare -a LINE
   declare -a DEVICES
   declare -a SIZES
   declare -a NAMES
   DEVICE=0;
-  while read LINE; do
-    if grep -q 'description: ' <<< "$LINE"; then
+  while IFS=":" read -r -a LINE; do
+  case "${LINE[0]}" in
+    *"description")
       DEVICE=$((DEVICE+1))
       DEVICES[$DEVICE]=""
       SIZES[$DEVICE]=""
       NAMES[$DEVICE]=""
-    elif grep -q 'logical name: ' <<< "$LINE"; then
-      DEVICES[$DEVICE]="`cut -d':' -f2 <<< $LINE`"
-    elif grep -q 'size:' <<< "$LINE"; then
-      SIZES[$DEVICE]+="`cut -d':' -f2 <<< $LINE`"
-    elif grep -q 'product: ' <<< "$LINE"; then
-      NAMES[$DEVICE]+="`cut -d':' -f2 <<< $LINE`"
-    fi
+      ;;
+    *"logical name")
+      DEVICES[$DEVICE]="${LINE[1]# }"
+      ;;
+    *"size")
+      SIZES[$DEVICE]+="${LINE[1]# }"
+      ;;
+    *"product")
+      NAMES[$DEVICE]+="${LINE[1]# }"
+      ;;
+  esac
   done < <(sudo lshw -class disk 2> /dev/null)
+  unset LINE
 
   # Display a list of options
   echo
   DEFAULTSELECT=0
   for I in "${!DEVICES[@]}"; do
     if [[ "${SIZES[$I]}" ]]; then
-      echo "$I) ${DEVICES[$I]} ${NAMES[$I]}${SIZES[$I]}"
+      echo "$I) ${DEVICES[$I]} ${NAMES[$I]} (${SIZES[$I]})"
     else
       echo "$I) ${DEVICES[$I]} ${NAMES[$I]} (currently empty)"
     fi
@@ -99,7 +106,7 @@ else
   echo
   DEV=""
   while ! [[ "$DEV" ]]; do
-    read -p "Please select your device [$DEFAULTSELECT]: " SELECTED
+    read -rp "Please select your device [$DEFAULTSELECT]: " SELECTED
     if ! [[ "$SELECTED" ]]; then
       SELECTED=$DEFAULTSELECT
     fi
@@ -120,7 +127,7 @@ if [[ ! -b "$DEV" ]]; then
 fi
 
 # Confirm
-read -p "Restore from $FILE to $DEV is that correct? [y/N]: " -n1 AGREE
+read -rp "Restore from $FILE to $DEV is that correct? [y/N]: " -n1 AGREE
 if ! [[ "$AGREE" =~ ^[yY]$ ]]; then
   exit
 fi
@@ -128,36 +135,37 @@ echo
 echo
 
 # Filenames
-LOCKFILE="$TEMPFOLDER/`echo "$DEV" | tr "/" "_"`.lock"
-TEMPFILE="$TEMPFOLDER/`echo "$FILE_$DEV" | tr "/" "_"`.tempfile"
-ERRFILE="$TEMPFOLDER/`echo "$FILE_$DEV" | tr "/" "_"`.error"
+LOCKFILE="/tmp/sdbackup${DEV////_}.lock"
+TEMPFILE="$TEMPFOLDER/${FILE}_${DEV////_}.tempfile"
+ERRFILE="$TEMPFOLDER/${FILE}_${DEV////_}.error"
 
 # Test and create lockfile
 if [[ -f $LOCKFILE ]]; then
-  echo "Error: There is a `cat $LOCKFILE` currently running on $DEV" 1>&2;
+  echo "Error: There is a $(cat "$LOCKFILE") currently running on $DEV" 1>&2;
   exit 1;
 fi
-echo $THISAPP > $LOCKFILE
+echo "$THISAPP ($$)" > "$LOCKFILE"
 
 # Trap for failure
-trap 'rm "$LOCKFILE" 2> /dev/null; rm "$TEMPFILE" 2> /dev/null; rm "$ERRFILE" 2> /dev/null' EXIT
+trap 'rm "$LOCKFILE" 2> /dev/null; rm "$TEMPFILE" 2> /dev/null; rm "$ERRFILE" 2> /dev/null; rmdir "$TEMPFOLDER" 2> /dev/null' EXIT
 
 # Clean up anything left over from a previous attempt
-sudo rm "$TEMPFILE" 2> /dev/null
-sudo rm "$ERRFILE" 2> /dev/null
+sudo rm "/tmp/sdbackup.tmp."*/*.tempfile 2> /dev/null
+sudo rm "/tmp/sdbackup.tmp."*/*.error 2> /dev/null
+sudo rmdir "/tmp/sdbackup.tmp."* 2> /dev/null
 
 # Unmount the card
 echo "Unmounting any mounted partitions..."
 for PARTITION in "$DEV"*; do
   if [[ -b "$PARTITION" ]]; then
-    if egrep -qs ^"$PARTITION " /proc/mounts; then
+    if grep -Eqs ^"$PARTITION " /proc/mounts; then
       sudo umount "$PARTITION" 2> /dev/null || { echo "Error: Cannot unmount $PARTITION" 1>&2; exit 1; }
     fi
   fi
 done
 
 # See if the file needs decompressing
-if [[ "`file \"$FILE\" | grep 'compressed\|archive'`" ]]; then
+if file \"$FILE\" | grep -q 'compressed\|archive'; then
   # Decompress the file
   echo "Decompressing..."
   ucat "$FILE" > "$TEMPFILE" 2> "$ERRFILE" || { echo "Error: Cannot decompress $FILE" 1>&2; exit 1; }
@@ -172,13 +180,13 @@ else
 fi
 
 # Check its not still compressed
-if [[ "`file \"$RESTOREFILE\" | grep 'compressed\|archive'`" ]]; then
+if file \"$RESTOREFILE\" | grep -q 'compressed\|archive'; then
   echo "Error: Cannot decompress $FILE" 1>&2;
   exit 1;
 fi
 
 # Restore the file
-echo "Restoring "`ls -lah "$RESTOREFILE" | awk -F " " {'print $5'}`" to $DEV..."
+echo "Restoring $(ls -lah "$RESTOREFILE" | awk -F " " '{print $5}') bytes to $DEV..."
 echo
 sudo ddrescue --force --synchronous "$RESTOREFILE" "$DEV" || exit 1;
 echo
